---
title: "Weight of Fish"
author: "Steven Garcia"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
library(dplyr)
library(leaps)
fish = read_csv("Fish.csv")
```

# Predicting Fish Weight

Find the best model using 2 variables to predict Perch weight, and compare this to the best overall model. 

## Perch

```{r}
perch = filter(fish, Species == 'Perch')
```


### Best Two regressor model

```{r}
modelperch = regsubsets(Weight ~ Length1 + Length2 + Length3 + Height + Width, data = perch, )
summary(modelperch)
```


```{r}
bestperch = lm(Weight ~ Height + Width, data = perch)
summary(bestperch)
```

## Best 2 variable equation

Weight = -536 + 74.77*Height + 69.62*Width


## Pike

```{r}
pike = filter(fish, Species == 'pike')
```

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements